# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js
node_js:
    - 14.16.0
# create cronjobs
resources:
  - name: test_running 
    type: time
    versionTemplate:
      interval: "32 * * * *"
jobs:                                    
  - name: sample_node_runCI              
    type: runCI                         
    steps:                               
      - IN: test_running              
    on_success:                          
      - script: echo 'on success !!!!!'  
    on_failure:                          
      - script: echo 'Failed job .... :('
